[package]
name = "spottedcat_ecs"
version = "0.0.1"
edition = "2021"
authors = ["Arion <arion.dsh@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "SpottedCat ECS"
repository = "https://github.com/arion-dsh/spottedcat"


