/// Represents a physical key on a keyboard.
///
/// This enum covers standard US-layout keys and is used by the [`InputManager`]
/// to track key states.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum Key {
    A = 0,
    B = 1,
    C = 2,
    D = 3,
    E = 4,
    F = 5,
    G = 6,
    H = 7,
    I = 8,
    J = 9,
    K = 10,
    L = 11,
    M = 12,
    N = 13,
    O = 14,
    P = 15,
    Q = 16,
    R = 17,
    S = 18,
    T = 19,
    U = 20,
    V = 21,
    W = 22,
    X = 23,
    Y = 24,
    Z = 25,

    Num0 = 26,
    Num1 = 27,
    Num2 = 28,
    Num3 = 29,
    Num4 = 30,
    Num5 = 31,
    Num6 = 32,
    Num7 = 33,
    Num8 = 34,
    Num9 = 35,

    Escape = 36,
    Enter = 37,
    Space = 38,
    Tab = 39,
    Backspace = 40,

    Left = 41,
    Right = 42,
    Up = 43,
    Down = 44,

    LShift = 45,
    RShift = 46,
    LCtrl = 47,
    RCtrl = 48,
    LAlt = 49,
    RAlt = 50,

    CapsLock = 51,

    Insert = 52,
    Delete = 53,
    Home = 54,
    End = 55,
    PageUp = 56,
    PageDown = 57,

    PrintScreen = 58,
    ScrollLock = 59,
    Pause = 60,

    F1 = 61,
    F2 = 62,
    F3 = 63,
    F4 = 64,
    F5 = 65,
    F6 = 66,
    F7 = 67,
    F8 = 68,
    F9 = 69,
    F10 = 70,
    F11 = 71,
    F12 = 72,

    Minus = 73,
    Equal = 74,
    BracketLeft = 75,
    BracketRight = 76,
    Backslash = 77,
    Semicolon = 78,
    Quote = 79,
    Backquote = 80,
    Comma = 81,
    Period = 82,
    Slash = 83,

    NumLock = 84,
    Numpad0 = 85,
    Numpad1 = 86,
    Numpad2 = 87,
    Numpad3 = 88,
    Numpad4 = 89,
    Numpad5 = 90,
    Numpad6 = 91,
    Numpad7 = 92,
    Numpad8 = 93,
    Numpad9 = 94,
    NumpadAdd = 95,
    NumpadSubtract = 96,
    NumpadMultiply = 97,
    NumpadDivide = 98,
    NumpadEnter = 99,
    NumpadDecimal = 100,
}

impl Key {
    pub const COUNT: usize = (Key::NumpadDecimal as usize) + 1;
    pub const WORDS: usize = Self::COUNT.div_ceil(64);

    pub const fn as_index(self) -> usize {
        self as usize
    }

    pub(crate) fn from_sdl_scancode(code: sdl3_sys::scancode::SDL_Scancode) -> Option<Self> {
        use sdl3_sys::scancode::*;
        Some(match code {
            SDL_SCANCODE_A => Key::A,
            SDL_SCANCODE_B => Key::B,
            SDL_SCANCODE_C => Key::C,
            SDL_SCANCODE_D => Key::D,
            SDL_SCANCODE_E => Key::E,
            SDL_SCANCODE_F => Key::F,
            SDL_SCANCODE_G => Key::G,
            SDL_SCANCODE_H => Key::H,
            SDL_SCANCODE_I => Key::I,
            SDL_SCANCODE_J => Key::J,
            SDL_SCANCODE_K => Key::K,
            SDL_SCANCODE_L => Key::L,
            SDL_SCANCODE_M => Key::M,
            SDL_SCANCODE_N => Key::N,
            SDL_SCANCODE_O => Key::O,
            SDL_SCANCODE_P => Key::P,
            SDL_SCANCODE_Q => Key::Q,
            SDL_SCANCODE_R => Key::R,
            SDL_SCANCODE_S => Key::S,
            SDL_SCANCODE_T => Key::T,
            SDL_SCANCODE_U => Key::U,
            SDL_SCANCODE_V => Key::V,
            SDL_SCANCODE_W => Key::W,
            SDL_SCANCODE_X => Key::X,
            SDL_SCANCODE_Y => Key::Y,
            SDL_SCANCODE_Z => Key::Z,

            SDL_SCANCODE_0 => Key::Num0,
            SDL_SCANCODE_1 => Key::Num1,
            SDL_SCANCODE_2 => Key::Num2,
            SDL_SCANCODE_3 => Key::Num3,
            SDL_SCANCODE_4 => Key::Num4,
            SDL_SCANCODE_5 => Key::Num5,
            SDL_SCANCODE_6 => Key::Num6,
            SDL_SCANCODE_7 => Key::Num7,
            SDL_SCANCODE_8 => Key::Num8,
            SDL_SCANCODE_9 => Key::Num9,

            SDL_SCANCODE_ESCAPE => Key::Escape,
            SDL_SCANCODE_RETURN => Key::Enter,
            SDL_SCANCODE_SPACE => Key::Space,
            SDL_SCANCODE_TAB => Key::Tab,
            SDL_SCANCODE_BACKSPACE => Key::Backspace,

            SDL_SCANCODE_LEFT => Key::Left,
            SDL_SCANCODE_RIGHT => Key::Right,
            SDL_SCANCODE_UP => Key::Up,
            SDL_SCANCODE_DOWN => Key::Down,

            SDL_SCANCODE_LSHIFT => Key::LShift,
            SDL_SCANCODE_RSHIFT => Key::RShift,
            SDL_SCANCODE_LCTRL => Key::LCtrl,
            SDL_SCANCODE_RCTRL => Key::RCtrl,
            SDL_SCANCODE_LALT => Key::LAlt,
            SDL_SCANCODE_RALT => Key::RAlt,

            SDL_SCANCODE_CAPSLOCK => Key::CapsLock,

            SDL_SCANCODE_INSERT => Key::Insert,
            SDL_SCANCODE_DELETE => Key::Delete,
            SDL_SCANCODE_HOME => Key::Home,
            SDL_SCANCODE_END => Key::End,
            SDL_SCANCODE_PAGEUP => Key::PageUp,
            SDL_SCANCODE_PAGEDOWN => Key::PageDown,

            SDL_SCANCODE_PRINTSCREEN => Key::PrintScreen,
            SDL_SCANCODE_SCROLLLOCK => Key::ScrollLock,
            SDL_SCANCODE_PAUSE => Key::Pause,

            SDL_SCANCODE_F1 => Key::F1,
            SDL_SCANCODE_F2 => Key::F2,
            SDL_SCANCODE_F3 => Key::F3,
            SDL_SCANCODE_F4 => Key::F4,
            SDL_SCANCODE_F5 => Key::F5,
            SDL_SCANCODE_F6 => Key::F6,
            SDL_SCANCODE_F7 => Key::F7,
            SDL_SCANCODE_F8 => Key::F8,
            SDL_SCANCODE_F9 => Key::F9,
            SDL_SCANCODE_F10 => Key::F10,
            SDL_SCANCODE_F11 => Key::F11,
            SDL_SCANCODE_F12 => Key::F12,

            SDL_SCANCODE_MINUS => Key::Minus,
            SDL_SCANCODE_EQUALS => Key::Equal,
            SDL_SCANCODE_LEFTBRACKET => Key::BracketLeft,
            SDL_SCANCODE_RIGHTBRACKET => Key::BracketRight,
            SDL_SCANCODE_BACKSLASH => Key::Backslash,
            SDL_SCANCODE_SEMICOLON => Key::Semicolon,
            SDL_SCANCODE_APOSTROPHE => Key::Quote,
            SDL_SCANCODE_GRAVE => Key::Backquote,
            SDL_SCANCODE_COMMA => Key::Comma,
            SDL_SCANCODE_PERIOD => Key::Period,
            SDL_SCANCODE_SLASH => Key::Slash,

            SDL_SCANCODE_NUMLOCKCLEAR => Key::NumLock,
            SDL_SCANCODE_KP_0 => Key::Numpad0,
            SDL_SCANCODE_KP_1 => Key::Numpad1,
            SDL_SCANCODE_KP_2 => Key::Numpad2,
            SDL_SCANCODE_KP_3 => Key::Numpad3,
            SDL_SCANCODE_KP_4 => Key::Numpad4,
            SDL_SCANCODE_KP_5 => Key::Numpad5,
            SDL_SCANCODE_KP_6 => Key::Numpad6,
            SDL_SCANCODE_KP_7 => Key::Numpad7,
            SDL_SCANCODE_KP_8 => Key::Numpad8,
            SDL_SCANCODE_KP_9 => Key::Numpad9,
            SDL_SCANCODE_KP_PLUS => Key::NumpadAdd,
            SDL_SCANCODE_KP_MINUS => Key::NumpadSubtract,
            SDL_SCANCODE_KP_MULTIPLY => Key::NumpadMultiply,
            SDL_SCANCODE_KP_DIVIDE => Key::NumpadDivide,
            SDL_SCANCODE_KP_ENTER => Key::NumpadEnter,
            SDL_SCANCODE_KP_PERIOD => Key::NumpadDecimal,

            _ => return None,
        })
    }
}
